# Default values for geodata-complete.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  api: 1
  web: 1

image: 
  pullPolicy: Always
  geodataRest: ag04/geodata-rest-sb:latest
  geodataWeb: ag04/geodata-ng:latest

namespace: 
  create: true
  name: geodata

# Postgres configuration
postgres:
  deploy: true
  port: 5432
  container:
    image: postgres:13.5
  host:
    address: host.minikube.internal
  database:
    name: geodata
    user: geodata
    password: geodatapwd
    schema: public
  persistentStorage:
    enabled: true
    baseName: geodata-pg
    size: 5Gi
    hostPath: "/mnt/minikube/postgres-data"

# Ingress options
ingress:
  enabled: true
  host: geodata.local-minikube.io

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 6

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

# application options
geodata:
  spring_profiles_active: prod,api-docs
  liquibase:
    enabled: true
    contexts: "dev"
  protocol: http
  host: geodata.local-minikube.io
  path: /
  mail:
    host: localhost
    user: yyyyyyyy
    password: xxxxxxxxx
    from: geodata@workshop.ag04.io
  max_pool_size: 5