kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-web-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.replicaCount.web }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      deploy: {{ .Release.Name }}-web
  template:      
    metadata:
      labels:
        app: {{ .Release.Name }}-web
        deploy: {{ .Release.Name }}-web
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.image.geodataWeb }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: GEODATA_API_URL
            value: "http://{{ .Release.Name }}-rest-service:8080/api"
          - name: GEODATA_MNGMT_URL
            value: "http://{{ .Release.Name }}-rest-service:8080/management"
          - name: GEODATA_SWAGGER_URL
            value: "http://{{ .Release.Name }}-rest-service:8080/v3"
          - name: GEODATA_AUTH_URL
            value: "http://{{ .Release.Name }}-rest-service:8081/auth"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: '64Mi'
              cpu: '150m'
            limits:
              memory: '128Mi'
              cpu: '300m'
