{{- if .Values.postgres.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: {{ .Release.Name }}-postgres
          image: {{ .Values.postgres.container.image }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database.name }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.database.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.database.password }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.persistentStorage.baseName }}-pv-claim
{{- end }}