apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  geodata_db_pwd: {{ .Values.postgres.database.password | b64enc }}
  geodata_mail_pwd: {{ .Values.geodata.mail.password | b64enc }}
  {{ if .Values.geodata.infinispan.enabled }}
  infinispan_pwd: "{{ .Values.geodata.infinispan.pwd | b64enc }}"
  {{ end }}