apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rest-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Release.Name }}-rest-service
spec:
  selector:
    app: {{ .Release.Name }}-rest
  ports:
    - name: http
      port: 8080