{{- if .Values.postgres.deploy }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.persistentStorage.baseName }}-pv
  namespace: {{ .Values.namespace.name }}
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.persistentStorage.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.postgres.persistentStorage.hostPath }}
{{- end }}